title: "NUP Robotics Lab"
description: "Site for NUP Robotics Lab"
baseurl: ""
url: "https://robocy.org"

markdown: kramdown
theme: null
collections:
  projects:
    output: true
    permalink: /projects/:name/
  schools:
    output: true
    permalink: /schools/:name/